/*
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ScaleEditor extends XbaseEditor {
}
