/*
 * generated by Xtext 2.16.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mdeoptimiser.languages.parser.antlr.internal.InternalScaleSearchParser;
import uk.ac.kcl.inf.mdeoptimiser.languages.services.ScaleSearchGrammarAccess;

public class ScaleSearchParser extends AbstractAntlrParser {

	@Inject
	private ScaleSearchGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalScaleSearchParser createParser(XtextTokenStream stream) {
		return new InternalScaleSearchParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Scale";
	}

	public ScaleSearchGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScaleSearchGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
