/*
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ScaleUiModule extends AbstractScaleUiModule {

	public ScaleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
