/*
 * generated by Xtext 2.16.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScaleRuntimeModule extends AbstractScaleRuntimeModule {
}
