/**
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.meerkat;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Analyser</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Analyser#getProblems <em>Problems</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getAnalyser()
 * @model
 * @generated
 */
public interface Analyser extends EObject
{
  /**
   * Returns the value of the '<em><b>Problems</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Problems</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Problems</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getAnalyser_Problems()
   * @model containment="true"
   * @generated
   */
  EList<Problem> getProblems();

} // Analyser
