/**
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.meerkat;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatFactory
 * @model kind="package"
 * @generated
 */
public interface MeerkatPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "meerkat";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/mdeoptimiser/languages/Meerkat";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "meerkat";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MeerkatPackage eINSTANCE = uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalyserImpl <em>Analyser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalyserImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getAnalyser()
   * @generated
   */
  int ANALYSER = 0;

  /**
   * The feature id for the '<em><b>Problems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYSER__PROBLEMS = 0;

  /**
   * The number of structural features of the '<em>Analyser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYSER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemImpl <em>Problem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getProblem()
   * @generated
   */
  int PROBLEM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Configuration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM__CONFIGURATION = 1;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM__MODELS = 2;

  /**
   * The feature id for the '<em><b>Analysis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM__ANALYSIS = 3;

  /**
   * The number of structural features of the '<em>Problem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemConfigurationImpl <em>Problem Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemConfigurationImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getProblemConfiguration()
   * @generated
   */
  int PROBLEM_CONFIGURATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Objective</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION__OBJECTIVE = 1;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION__CONSTRAINT = 2;

  /**
   * The feature id for the '<em><b>Batches</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION__BATCHES = 3;

  /**
   * The feature id for the '<em><b>Termination Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION__TERMINATION_CONDITION = 4;

  /**
   * The number of structural features of the '<em>Problem Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEM_CONFIGURATION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ModelImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getModel()
   * @generated
   */
  int MODEL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Tools</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TOOLS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalysisConfigurationImpl <em>Analysis Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalysisConfigurationImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getAnalysisConfiguration()
   * @generated
   */
  int ANALYSIS_CONFIGURATION = 4;

  /**
   * The feature id for the '<em><b>Reference Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYSIS_CONFIGURATION__REFERENCE_SET = 0;

  /**
   * The feature id for the '<em><b>Summary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYSIS_CONFIGURATION__SUMMARY = 1;

  /**
   * The number of structural features of the '<em>Analysis Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANALYSIS_CONFIGURATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.SummaryImpl <em>Summary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.SummaryImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getSummary()
   * @generated
   */
  int SUMMARY = 5;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUMMARY__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Summary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUMMARY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ObjectiveImpl <em>Objective</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ObjectiveImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getObjective()
   * @generated
   */
  int OBJECTIVE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__NAME = 0;

  /**
   * The number of structural features of the '<em>Objective</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ConstraintImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__NAME = 0;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.BatchesImpl <em>Batches</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.BatchesImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getBatches()
   * @generated
   */
  int BATCHES = 8;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BATCHES__NUMBER = 0;

  /**
   * The number of structural features of the '<em>Batches</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BATCHES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.TerminationConditionImpl <em>Termination Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.TerminationConditionImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getTerminationCondition()
   * @generated
   */
  int TERMINATION_CONDITION = 9;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATION_CONDITION__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Termination Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATION_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolImpl <em>Tool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getTool()
   * @generated
   */
  int TOOL = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL__NAME = 0;

  /**
   * The feature id for the '<em><b>Configurations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL__CONFIGURATIONS = 1;

  /**
   * The number of structural features of the '<em>Tool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolConfigurationImpl <em>Tool Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolConfigurationImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getToolConfiguration()
   * @generated
   */
  int TOOL_CONFIGURATION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_CONFIGURATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_CONFIGURATION__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Tool Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_CONFIGURATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ReferenceSetImpl <em>Reference Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ReferenceSetImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getReferenceSet()
   * @generated
   */
  int REFERENCE_SET = 12;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_SET__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Reference Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_SET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VALUE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterValueImpl <em>Parameter Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterValueImpl
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getParameterValue()
   * @generated
   */
  int PARAMETER_VALUE = 14;

  /**
   * The feature id for the '<em><b>Numeric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VALUE__NUMERIC = 0;

  /**
   * The feature id for the '<em><b>Functional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VALUE__FUNCTIONAL = 1;

  /**
   * The feature id for the '<em><b>Parametric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VALUE__PARAMETRIC = 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VALUE__PARAMS = 3;

  /**
   * The number of structural features of the '<em>Parameter Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VALUE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Analyser <em>Analyser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Analyser</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Analyser
   * @generated
   */
  EClass getAnalyser();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Analyser#getProblems <em>Problems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Problems</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Analyser#getProblems()
   * @see #getAnalyser()
   * @generated
   */
  EReference getAnalyser_Problems();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem <em>Problem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Problem</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem
   * @generated
   */
  EClass getProblem();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getName()
   * @see #getProblem()
   * @generated
   */
  EAttribute getProblem_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getConfiguration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Configuration</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getConfiguration()
   * @see #getProblem()
   * @generated
   */
  EReference getProblem_Configuration();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Models</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getModels()
   * @see #getProblem()
   * @generated
   */
  EReference getProblem_Models();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getAnalysis <em>Analysis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Analysis</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Problem#getAnalysis()
   * @see #getProblem()
   * @generated
   */
  EReference getProblem_Analysis();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration <em>Problem Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Problem Configuration</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration
   * @generated
   */
  EClass getProblemConfiguration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getName()
   * @see #getProblemConfiguration()
   * @generated
   */
  EAttribute getProblemConfiguration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getObjective <em>Objective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objective</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getObjective()
   * @see #getProblemConfiguration()
   * @generated
   */
  EReference getProblemConfiguration_Objective();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraint</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getConstraint()
   * @see #getProblemConfiguration()
   * @generated
   */
  EReference getProblemConfiguration_Constraint();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getBatches <em>Batches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Batches</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getBatches()
   * @see #getProblemConfiguration()
   * @generated
   */
  EReference getProblemConfiguration_Batches();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getTerminationCondition <em>Termination Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Termination Condition</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getTerminationCondition()
   * @see #getProblemConfiguration()
   * @generated
   */
  EReference getProblemConfiguration_TerminationCondition();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model#getTools <em>Tools</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tools</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Model#getTools()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tools();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration <em>Analysis Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Analysis Configuration</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration
   * @generated
   */
  EClass getAnalysisConfiguration();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration#getReferenceSet <em>Reference Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reference Set</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration#getReferenceSet()
   * @see #getAnalysisConfiguration()
   * @generated
   */
  EReference getAnalysisConfiguration_ReferenceSet();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration#getSummary <em>Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Summary</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.AnalysisConfiguration#getSummary()
   * @see #getAnalysisConfiguration()
   * @generated
   */
  EReference getAnalysisConfiguration_Summary();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Summary <em>Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Summary</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Summary
   * @generated
   */
  EClass getSummary();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Summary#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Summary#getParameters()
   * @see #getSummary()
   * @generated
   */
  EReference getSummary_Parameters();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Objective <em>Objective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objective</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Objective
   * @generated
   */
  EClass getObjective();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Objective#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Objective#getName()
   * @see #getObjective()
   * @generated
   */
  EAttribute getObjective_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Constraint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Constraint#getName()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Batches <em>Batches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Batches</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Batches
   * @generated
   */
  EClass getBatches();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Batches#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Batches#getNumber()
   * @see #getBatches()
   * @generated
   */
  EAttribute getBatches_Number();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.TerminationCondition <em>Termination Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termination Condition</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.TerminationCondition
   * @generated
   */
  EClass getTerminationCondition();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.TerminationCondition#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.TerminationCondition#getParameters()
   * @see #getTerminationCondition()
   * @generated
   */
  EReference getTerminationCondition_Parameters();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool <em>Tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tool</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool
   * @generated
   */
  EClass getTool();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool#getName()
   * @see #getTool()
   * @generated
   */
  EAttribute getTool_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool#getConfigurations <em>Configurations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configurations</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Tool#getConfigurations()
   * @see #getTool()
   * @generated
   */
  EReference getTool_Configurations();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration <em>Tool Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tool Configuration</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration
   * @generated
   */
  EClass getToolConfiguration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration#getName()
   * @see #getToolConfiguration()
   * @generated
   */
  EAttribute getToolConfiguration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ToolConfiguration#getParameters()
   * @see #getToolConfiguration()
   * @generated
   */
  EReference getToolConfiguration_Parameters();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ReferenceSet <em>Reference Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Set</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ReferenceSet
   * @generated
   */
  EClass getReferenceSet();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ReferenceSet#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ReferenceSet#getLocation()
   * @see #getReferenceSet()
   * @generated
   */
  EAttribute getReferenceSet_Location();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Parameter#getValue()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue <em>Parameter Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Value</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue
   * @generated
   */
  EClass getParameterValue();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getNumeric <em>Numeric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numeric</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getNumeric()
   * @see #getParameterValue()
   * @generated
   */
  EAttribute getParameterValue_Numeric();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getFunctional <em>Functional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Functional</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getFunctional()
   * @see #getParameterValue()
   * @generated
   */
  EAttribute getParameterValue_Functional();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getParametric <em>Parametric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parametric</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getParametric()
   * @see #getParameterValue()
   * @generated
   */
  EAttribute getParameterValue_Parametric();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ParameterValue#getParams()
   * @see #getParameterValue()
   * @generated
   */
  EReference getParameterValue_Params();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MeerkatFactory getMeerkatFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalyserImpl <em>Analyser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalyserImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getAnalyser()
     * @generated
     */
    EClass ANALYSER = eINSTANCE.getAnalyser();

    /**
     * The meta object literal for the '<em><b>Problems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANALYSER__PROBLEMS = eINSTANCE.getAnalyser_Problems();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemImpl <em>Problem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getProblem()
     * @generated
     */
    EClass PROBLEM = eINSTANCE.getProblem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROBLEM__NAME = eINSTANCE.getProblem_Name();

    /**
     * The meta object literal for the '<em><b>Configuration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM__CONFIGURATION = eINSTANCE.getProblem_Configuration();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM__MODELS = eINSTANCE.getProblem_Models();

    /**
     * The meta object literal for the '<em><b>Analysis</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM__ANALYSIS = eINSTANCE.getProblem_Analysis();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemConfigurationImpl <em>Problem Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ProblemConfigurationImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getProblemConfiguration()
     * @generated
     */
    EClass PROBLEM_CONFIGURATION = eINSTANCE.getProblemConfiguration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROBLEM_CONFIGURATION__NAME = eINSTANCE.getProblemConfiguration_Name();

    /**
     * The meta object literal for the '<em><b>Objective</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM_CONFIGURATION__OBJECTIVE = eINSTANCE.getProblemConfiguration_Objective();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM_CONFIGURATION__CONSTRAINT = eINSTANCE.getProblemConfiguration_Constraint();

    /**
     * The meta object literal for the '<em><b>Batches</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM_CONFIGURATION__BATCHES = eINSTANCE.getProblemConfiguration_Batches();

    /**
     * The meta object literal for the '<em><b>Termination Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEM_CONFIGURATION__TERMINATION_CONDITION = eINSTANCE.getProblemConfiguration_TerminationCondition();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ModelImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Tools</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TOOLS = eINSTANCE.getModel_Tools();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalysisConfigurationImpl <em>Analysis Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.AnalysisConfigurationImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getAnalysisConfiguration()
     * @generated
     */
    EClass ANALYSIS_CONFIGURATION = eINSTANCE.getAnalysisConfiguration();

    /**
     * The meta object literal for the '<em><b>Reference Set</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANALYSIS_CONFIGURATION__REFERENCE_SET = eINSTANCE.getAnalysisConfiguration_ReferenceSet();

    /**
     * The meta object literal for the '<em><b>Summary</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANALYSIS_CONFIGURATION__SUMMARY = eINSTANCE.getAnalysisConfiguration_Summary();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.SummaryImpl <em>Summary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.SummaryImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getSummary()
     * @generated
     */
    EClass SUMMARY = eINSTANCE.getSummary();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUMMARY__PARAMETERS = eINSTANCE.getSummary_Parameters();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ObjectiveImpl <em>Objective</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ObjectiveImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getObjective()
     * @generated
     */
    EClass OBJECTIVE = eINSTANCE.getObjective();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECTIVE__NAME = eINSTANCE.getObjective_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ConstraintImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__NAME = eINSTANCE.getConstraint_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.BatchesImpl <em>Batches</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.BatchesImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getBatches()
     * @generated
     */
    EClass BATCHES = eINSTANCE.getBatches();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BATCHES__NUMBER = eINSTANCE.getBatches_Number();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.TerminationConditionImpl <em>Termination Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.TerminationConditionImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getTerminationCondition()
     * @generated
     */
    EClass TERMINATION_CONDITION = eINSTANCE.getTerminationCondition();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATION_CONDITION__PARAMETERS = eINSTANCE.getTerminationCondition_Parameters();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolImpl <em>Tool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getTool()
     * @generated
     */
    EClass TOOL = eINSTANCE.getTool();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOOL__NAME = eINSTANCE.getTool_Name();

    /**
     * The meta object literal for the '<em><b>Configurations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOOL__CONFIGURATIONS = eINSTANCE.getTool_Configurations();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolConfigurationImpl <em>Tool Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ToolConfigurationImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getToolConfiguration()
     * @generated
     */
    EClass TOOL_CONFIGURATION = eINSTANCE.getToolConfiguration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOOL_CONFIGURATION__NAME = eINSTANCE.getToolConfiguration_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOOL_CONFIGURATION__PARAMETERS = eINSTANCE.getToolConfiguration_Parameters();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ReferenceSetImpl <em>Reference Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ReferenceSetImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getReferenceSet()
     * @generated
     */
    EClass REFERENCE_SET = eINSTANCE.getReferenceSet();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCE_SET__LOCATION = eINSTANCE.getReferenceSet_Location();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__VALUE = eINSTANCE.getParameter_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterValueImpl <em>Parameter Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.ParameterValueImpl
     * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.impl.MeerkatPackageImpl#getParameterValue()
     * @generated
     */
    EClass PARAMETER_VALUE = eINSTANCE.getParameterValue();

    /**
     * The meta object literal for the '<em><b>Numeric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_VALUE__NUMERIC = eINSTANCE.getParameterValue_Numeric();

    /**
     * The meta object literal for the '<em><b>Functional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_VALUE__FUNCTIONAL = eINSTANCE.getParameterValue_Functional();

    /**
     * The meta object literal for the '<em><b>Parametric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_VALUE__PARAMETRIC = eINSTANCE.getParameterValue_Parametric();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_VALUE__PARAMS = eINSTANCE.getParameterValue_Params();

  }

} //MeerkatPackage
