/**
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.meerkat;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Problem Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getObjective <em>Objective</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getConstraint <em>Constraint</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getBatches <em>Batches</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getTerminationCondition <em>Termination Condition</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration()
 * @model
 * @generated
 */
public interface ProblemConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objective</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Objective}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration_Objective()
   * @model containment="true"
   * @generated
   */
  EList<Objective> getObjective();

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.Constraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration_Constraint()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getConstraint();

  /**
   * Returns the value of the '<em><b>Batches</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Batches</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batches</em>' containment reference.
   * @see #setBatches(Batches)
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration_Batches()
   * @model containment="true"
   * @generated
   */
  Batches getBatches();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.ProblemConfiguration#getBatches <em>Batches</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batches</em>' containment reference.
   * @see #getBatches()
   * @generated
   */
  void setBatches(Batches value);

  /**
   * Returns the value of the '<em><b>Termination Condition</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.TerminationCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Termination Condition</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termination Condition</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.meerkat.MeerkatPackage#getProblemConfiguration_TerminationCondition()
   * @model containment="true"
   * @generated
   */
  EList<TerminationCondition> getTerminationCondition();

} // ProblemConfiguration
