package uk.ac.kcl.inf.mdeoptimiser.infrastructure.scale.jobs;

import uk.ac.kcl.inf.mdeoptimiser.infrastructure.scale.interpreter.experiments.tasks.types.ResultsTask;

import java.nio.file.Path;
import java.util.List;

/**
 * Class generated by each completed job executions. Contains pointers to the produced job artifacts such as
 * the accumulator and result files.
 */
public class ScaleJobResult {

  private Path accumulator;
  private List<Path> jobResultArtifacts;

  public Path getAccumulator() {
    return accumulator;
  }

  public void setAccumulator(Path accumulator) {
    this.accumulator = accumulator;
  }

  public List<Path> getJobResultArtifacts() {
    return jobResultArtifacts;
  }

  public void setJobResultArtifacts(List<Path> jobResultArtifacts) {
    this.jobResultArtifacts = jobResultArtifacts;
  }
}