/*
 * generated by Xtext 2.18.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uk.ac.kcl.inf.mdeoptimiser.languages.ui.internal.LanguagesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScaleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LanguagesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LanguagesActivator activator = LanguagesActivator.getInstance();
		return activator != null ? activator.getInjector(LanguagesActivator.UK_AC_KCL_INF_MDEOPTIMISER_LANGUAGES_SCALE) : null;
	}

}
