/**
 * generated by Xtext 2.16.0
 */
package uk.ac.kcl.inf.mdeoptimiser.languages.scale;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.scale.Scale#getInfrastructure <em>Infrastructure</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdeoptimiser.languages.scale.Scale#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdeoptimiser.languages.scale.ScalePackage#getScale()
 * @model
 * @generated
 */
public interface Scale extends EObject
{
  /**
   * Returns the value of the '<em><b>Infrastructure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Infrastructure</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infrastructure</em>' containment reference.
   * @see #setInfrastructure(Infrastructure)
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.scale.ScalePackage#getScale_Infrastructure()
   * @model containment="true"
   * @generated
   */
  Infrastructure getInfrastructure();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdeoptimiser.languages.scale.Scale#getInfrastructure <em>Infrastructure</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infrastructure</em>' containment reference.
   * @see #getInfrastructure()
   * @generated
   */
  void setInfrastructure(Infrastructure value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdeoptimiser.languages.scale.Task}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdeoptimiser.languages.scale.ScalePackage#getScale_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // Scale
